apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: sample-camel-log
    name: sample-camel-log
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    labels:
      app: sample-camel-log
    name: sample-camel-log
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: sample-camel-log:latest
    source:
      contextDir: karaf-sample
      git:
        uri: https://hernst@pforge.eso-io.com/git/cloud
        httpsProxy: http://debre-proxy:8080
        httpProxy: http://debre-proxy:8080
      sourceSecret:
        name: hernst
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: fis-karaf-openshift:latest
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange

kind: List
metadata: {}

