apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: amee-server
    name: centos
  spec:
    dockerImageRepository: library/centos
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: amee-server
    name: amee-server
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: amee-server
    name: amee-server
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: amee-server:latest
    resources: {}
    source:
      git:
        uri: https://pforge.eso-io.com/git/cloud
        httpProxy: http://debre-proxy:8080
        httpsProxy: http://debre-proxy:8080
      sourceSecret:
        name: hernst
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:latest
      type: Docker
    triggers:
    - github:
        secret: Vn0q_MCY6Crc-ArUTVwi
      type: GitHub
    - generic:
        secret: AsZ_04RR6UJrdGsgHFe8
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: amee-server
    name: amee-server
  spec:
    replicas: 1
    selector:
      app: amee-server
      deploymentconfig: amee-server
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: amee-server
          deploymentconfig: amee-server
      spec:
        containers:
        - image: library/amee-server:latest
          name: amee-server
          ports:
          - containerPort: 16842
            protocol: TCP
          resources: {}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - amee-server
        from:
          kind: ImageStreamTag
          name: amee-server:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: amee-server
    name: amee-server
  spec:
    ports:
    - name: 16842-tcp
      port: 16842
      protocol: TCP
      targetPort: 16842
    selector:
      app: amee-server
      deploymentconfig: amee-server
  status:
    loadBalancer: {}
kind: List
metadata: {}

