apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    creationTimestamp: null
    labels:
      app: 3dconjunction
    name: 3dconjunction
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      generatedby: OpenShiftWebConsole
      name: 3dconjunction
    name: 3dconjunction
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 3dconjunction:latest
    resources: {}
    source:
      git:
        ref: master
        uri: "https://pforge.eso-io.com/git/asteria"
        httpProxy: http://debre-proxy:8080
        httpsProxy: http://debre-proxy:8080
      sourceSecret:
        name: hernst
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: HTTP_PROXY
          value: http://debre-proxy:8080
        - name: HTTPS_PROXY
          value: https://debre-proxy:8080
        - name: MAVEN_ARGS
          value: clean install -s settings.xml -DproxyHost=debre-proxy -DproxyPort=8080 -DproxySet=true
        - name: ARTIFACT_DIR
          value: 3d-conjunction-webapp/trunk/target
        from:
          kind: ImageStreamTag
          name: jboss-webserver3-tomcat8-openshift:3.0
          namespace: openshift
      type: Source
    triggers:
    - generic:
        secret: 58a8453ab350ff6b
      type: Generic
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  data:
    password: UzB1dGhDMG1wIQ==
    username: aGVybnN0
  kind: Secret
  metadata:
    creationTimestamp: null
    name: hernst
  type: Opaque

